# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - run: npm run build
    - name: Dockerize
      if: success()
      uses: manusa/actions-publish-docker@master
      with:
        name: clabroche/docker
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        tag script: |
          return context.ref
            .replace('refs/heads/
            .replace('refs/tags/'
            .replace('refs/pull/'
            .replace(/\//g, '_')
            .replace(/#/g, '');
